/**
 * Customer-facing UI copy (Bangla-first, simple English where common on BD shops).
 */
export const bn = {
  brand: {
    codBanner: "সারা বাংলাদেশে ক্যাশ অন ডেলিভারি",
    codShort: "ক্যাশ অন ডেলিভারি · সারা বাংলাদেশে"
  },
  nav: {
    home: "হোম",
    shop: "শপ",
    contact: "যোগাযোগ",
    login: "লগইন",
    admin: "অ্যাডমিন",
    searchPlaceholder: "পণ্য খুঁজুন...",
    search: "খুঁজুন",
    wishlist: "পছন্দের তালিকা",
    cart: "কার্ট",
    noSearchResults: "কোনো পণ্য পাওয়া যায়নি"
  },
  categories: {
    all: "সব",
    "Salwar Kameez": "সালোয়ার কামিজ",
    "Two Pieces": "টু পিস",
    "Three Pieces": "থ্রি পিস",
    Frogs: "ফ্রগ",
    Gown: "গাউন",
    Plazo: "প্লাজো"
  },
  product: {
    addToCart: "কার্টে যোগ করুন",
    addedToCart: "যোগ হয়েছে ✓",
    buyNow: "এখনই অর্ডার করুন",
    orderNow: "অর্ডার করুন",
    chooseOptions: "সাইজ ও রঙ বেছে নিন",
    color: "রঙ",
    size: "সাইজ",
    selectSize: "সাইজ বেছে নিন",
    quantity: "পরিমাণ",
    inStock: "স্টকে আছে",
    items: "টি",
    cancel: "বাতিল",
    confirmAdd: "কার্টে যোগ করুন",
    selectColorSize: "আগে রঙ ও সাইজ বেছে নিন।",
    related: "আরও পণ্য",
    descriptions: "বিবরণ",
    specifications: "বিস্তারিত",
    reviews: "রিভিউ",
    brand: "ব্র্যান্ড",
    notFound: "পণ্যটি পাওয়া যায়নি",
    browseStore: "শপে যান",
    loading: "পণ্য লোড হচ্ছে..."
  },
  store: {
    title: "পোশাকের শপ",
    subtitle: "ক্যাশ অন ডেলিভারি · সারা বাংলাদেশে ডেলিভারি",
    loadError: "পণ্য লোড করা যায়নি। পেজ রিফ্রেশ করুন।"
  },
  home: {
    shopNow: "এখনই কিনুন →",
    shopByCategory: "ক্যাটাগরি অনুযায়ী",
    dealsOfWeek: "সপ্তাহের অফার",
    newArrival: "নতুন আগমন",
    flashDeal: "ফ্ল্যাশ ডিল",
    twoPieces: "টু পিস কালেকশন",
    threePieces: "থ্রি পিস কালেকশন"
  },
  cart: {
    title: "আপনার কার্ট",
    item: "টি পণ্য",
    items: "টি পণ্য",
    emptyTitle: "কার্ট খালি",
    emptyText: "এখনো কোনো পণ্য যোগ করেননি।",
    browse: "পণ্য দেখুন →",
    continueShopping: "← আরও কিনুন",
    clearCart: "কার্ট খালি করুন",
    clearConfirm: "কার্টের সব পণ্য মুছে ফেলবেন?",
    unit: "দাম",
    subtotal: "মোট পণ্য",
    delivery: "ডেলিভারি খরচ",
    deliveryNote: "চেকআউটে ঢাকা ভিতর/বাহির বেছে নেবেন",
    total: "মোট",
    summary: "অর্ডার সারাংশ",
    checkout: "অর্ডার সম্পন্ন করুন →",
    promo: "কুপন কোড",
    promoPlaceholder: "কুপন কোড লিখুন",
    apply: "প্রয়োগ"
  },
  checkout: {
    title: "অর্ডার করুন",
    breadcrumbHome: "হোম",
    breadcrumbCart: "কার্ট",
    breadcrumbCheckout: "অর্ডার",
    empty: "কার্ট খালি। আগে পণ্য যোগ করুন।",
    browse: "পণ্য দেখুন →",
    yourOrder: "আপনার অর্ডার",
    editCart: "কার্ট ঠিক করুন",
    qty: "পরিমাণ",
    billing: "আপনার তথ্য",
    fullName: "পুরো নাম *",
    namePlaceholder: "যেমন: ফাতেমা আক্তার",
    phone: "মোবাইল নম্বর *",
    phonePlaceholder: "যেমন: 01XXXXXXXXX",
    address: "সম্পূর্ণ ঠিকানা *",
    addressPlaceholder: "বাড়ি, রোড, এলাকা, জেলা",
    note: "বিশেষ নির্দেশনা",
    noteOptional: "(ঐচ্ছিক)",
    notePlaceholder: "রঙ, সাইজ বা ডেলিভারি নোট",
    summary: "বিল সারাংশ",
    subtotal: "পণ্যের মূল্য",
    deliveryArea: "ডেলিভারি এলাকা",
    insideDhaka: "ঢাকার ভিতরে",
    outsideDhaka: "ঢাকার বাহিরে",
    deliveryFee: "ডেলিভারি",
    totalPayable: "মোট পরিশোধ",
    cod: "ক্যাশ অন ডেলিভারি (পণ্য হাতে পেয়ে টাকা দিন)",
    terms: "আমি",
    termsLink: "শর্তাবলী",
    and: "ও",
    returnLink: "রিটার্ন নীতি",
    termsEnd: "মেনে নিচ্ছি",
    placing: "অর্ডার হচ্ছে…",
    confirm: "অর্ডার কনফার্ম করুন →",
    errors: {
      emptyCart: "কার্ট খালি।",
      required: "সব * চিহ্নিত ঘর পূরণ করুন।",
      phone: "সঠিক মোবাইল নম্বর দিন (১০–১৫ সংখ্যা)।",
      terms: "চালিয়ে যেতে শর্তাবলীতে সম্মতি দিন।",
      failed: "অর্ডার হয়নি। আবার চেষ্টা করুন।",
      network: "ইন্টারনেট সমস্যা। আবার চেষ্টা করুন।",
      noOrderId: "অর্ডার হয়েছে কিন্তু অর্ডার নম্বর পাওয়া যায়নি। সাপোর্টে কল করুন।"
    }
  },
  success: {
    title: "অর্ডার সফল হয়েছে",
    subtitle: "আপনার ক্যাশ অন ডেলিভারি অর্ডার গ্রহণ করা হয়েছে। নিচের তথ্য সংরক্ষণ করে রাখুন।",
    noOrder: "সাম্প্রতিক কোনো অর্ডার নেই।",
    continueShop: "আবার কিনুন",
    backStore: "শপে ফিরে যান",
    orderId: "অর্ডার নম্বর",
    placedOn: "অর্ডারের সময়",
    customer: "নাম",
    phone: "মোবাইল",
    address: "ডেলিভারি ঠিকানা",
    payment: "পেমেন্ট",
    paymentValue: "ক্যাশ অন ডেলিভারি",
    status: "স্ট্যাটাস",
    statusPending: "অপেক্ষমান — কনফার্ম করতে কল করব",
    statusConfirmed: "কনফার্ম হয়েছে",
    statusDelivered: "ডেলিভারি হয়েছে",
    statusCancelled: "বাতিল",
    itemsOrdered: "অর্ডারকৃত পণ্য",
    each: "প্রতিটি",
    line: "মোট",
    subtotal: "পণ্যের মূল্য",
    delivery: "ডেলিভারি",
    totalCod: "মোট (ক্যাশ অন ডেলিভারি)",
    yourNote: "আপনার নোট",
    footerNoteBefore: "ডেলিভারি কনফার্ম করতে",
    footerNoteAfter: "নম্বরে কল করব। অর্ডার নম্বর সংরক্ষণ করুন।"
  },
  footer: {
    categories: "ক্যাটাগরি",
    allProducts: "সব পণ্য",
    information: "তথ্য",
    contact: "যোগাযোগ",
    shipping: "ডেলিভারি নীতি",
    returns: "রিটার্ন নীতি",
    privacy: "গোপনীয়তা",
    terms: "শর্তাবলী",
    newsletter: "নিউজলেটার",
    newsletterText: "নতুন পণ্য ও অফার পেতে ইমেইল দিন।",
    emailPlaceholder: "আপনার ইমেইল",
    subscribe: "সাবস্ক্রাইব",
    rights: "সর্বস্বত্ব সংরক্ষিত",
    location: "ঢাকা, বাংলাদেশ"
  },
  wishlist: {
    title: "পছন্দের তালিকা",
    empty: "এখনো কোনো পণ্য সেভ করেননি।",
    browse: "পণ্য দেখুন →"
  }
} as const;

export function categoryLabelBn(category: string): string {
  const map = bn.categories as Record<string, string | undefined>;
  return map[category] ?? category;
}
